spring:
    application:
        name: jenkins

    jpa:
        open-in-view: false
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                highlight_sql: true
                auto_quote_keyword: true
                #globally_quoted_identifiers: true

logging:
    level:
        org.hibernate.orm.jdbc.bind: trace
        org.springframework.transaction.interceptor: trace
